### ISSUE TITLE
CreateServiceInstanceListeners issue

### ISSUE THREAD

**Issue by thdotnet** [Haishi2016/ProgrammingServiceFabric#2]
I was trying to follow the CalculatorService from your book, but it can't compile using the same code as your CreateServiceInstanceListeners method.

Mine only compile as:

```
protected override IEnumerable<ServiceInstanceListener> CreateServiceInstanceListeners()
        {
            return this.CreateServiceRemotingInstanceListeners();
        }
```

it seems that it has a thread about it too: https://social.msdn.microsoft.com/Forums/en-US/abd041f5-9e73-4b55-bc94-cf54603de81f/does-not-contain-a-definition-for-createserviceremotinglistener-and-no-extension-method?forum=AzureServiceFabric

can you help the right way? Is it something with dotnetcore 2.0 ?

**Comment by alessandro-avila** [comment]
I thdotnet,

make sure you have all of the needed assembly loaded, in particular Microsoft.ServiceFabric.Services.Remoting.

Here's my using region:

using CalculatorService.Interfaces;
using Microsoft.ServiceFabric.Services.Communication.Runtime;
using Microsoft.ServiceFabric.Services.Remoting.Runtime;
using Microsoft.ServiceFabric.Services.Runtime;
using System.Collections.Generic;
using System.Fabric;
using System.Threading.Tasks;

**Comment by alessandro-avila** [comment]
Hi @thdotnet, since didn't hear any feedback from you, I close this issue.
Please get in touch for any further clarification.
